### ISSUE TITLE
How to establish required SSH connection?

### ISSUE THREAD

**Issue by petric3** [ojwoodford/batch_job#1]
I tested your code "Batch Job" and works good on a single PC. Now, I would like to make it work across several PCs (in and outside of LAN) and have difficulties in setting up SSH connection. I am far from being an IT guy so SSH is new to me. Eventually I was able to establish SSH connection between two computers in LAN with freeSSHd program and Putty, but did not manage to make it work for the "Batch Job" purposes. I believe the programs violate the requirement that "All worker PCs can be ssh'd into non-interactively (i.e. without manually entering a password)" as the programs need user name and password and it seems they cannot work without it.

Kindly give a hint on how to establish the SSH connection between multiple PCs in order to make "Batch Job" work - what programs are best to use, procedure or any link or explanation on "How to" would be very welcome. Thank you so much.

**Comment by ojwoodford** [comment]
Try to follow some of the instructions in [this list](https://www.google.com/search?q=how+to+ssh+without+password) and see if they work for you.

**Comment by petric3** [comment]
The SSH connection seems to be made for Linux servers, which is according to online material rather easy to establish (with and also without password requirement), but seems hell with Windows systems, which are in my case on both PCs. It does work with Putty and freeSSHd via password, but not without it. Hence, I tried to install Cygwin on "server" PC, but after lots of errors did not work one way or another. There is also practically no or little material found on web, simply saying it's possible "windows to windows" but hard to establish "without password" option. Next thing is to install Linux, but unfortunately cannot do it as we use mostly windows-based programs. 

Please try to make another version of batch_job maybe just for Windows LAN users. I believe that would be appreciated by many users.

**Comment by ojwoodford** [comment]
I'm sure it would, but I'm not sure it's possible, and in any case I don't have the time. However, I have gotten this working on Windows, and it wasn't that hard:
- [Server](https://winscp.net/eng/docs/guide_windows_openssh_server)
- [Client](https://www.getfilecloud.com/blog/ssh-without-password-using-putty/)
