### ISSUE TITLE
getReport: basic vs. extended

### ISSUE THREAD

**Issue by spotlightgit** [ojwoodford/batch_job#10]
Is there any reason, why you explicitly selected 'basic' instead of the default 'extended' Report type?
do_chunk.m (line 27):
`output{b} = getReport(me, 'basic');`

Took me a while to find the reason for this:
> Error using horzcat
Dimensions of matrices being concatenated are not consistent.

Without knowing at which location to search …

Is it possible to change the report type to "extended"?

**Comment by ojwoodford** [comment]
I'll test this, and make the change if there are no issues.

**Comment by ojwoodford** [comment]
I've made this change.
