### ISSUE TITLE
Documentation unclear for use of "input" and "global_data"

### ISSUE THREAD

**Issue by jasonnicholson** [ojwoodford/batch_job#2]
I am having trouble understanding what you mean in the batch_job function documentation (the troublesome section is listed below). Please consider adding examples or demos of "global_data" use.

For instance, do you mean that _func_ is called like this without _global_data_ specified: `func(input(i)`)? When you use _globalData_, is it called like this instead: `func(globalData(i))`? Or is it this `func(input(i), globalData)`? Or something else?

Can you see how an example or demo would clear this up?

![clipboard01](https://cloud.githubusercontent.com/assets/1058191/25578863/ec2c0a30-2e72-11e7-9137-88782a54f97c.png)

**Comment by oliverwoodfordsc** [comment]
Good feedback. From memory I think it's `func(input(i), globalData)`, but I'll check and add an example soon. Thanks.

**Comment by oliverwoodfordsc** [comment]
The readme example makes it clear that it's `func(input(i), globalData)`. I'll add this the help text.

**Comment by jasonnicholson** [comment]
Okay. Thank you.

**Comment by ojwoodford** [comment]
I've updated the help text with some examples
