### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by lirantzafri** [ojwoodford/batch_job#7]
I've started using batch_job and it works great! I was wondering if you could add a license information to the repository though, which would make it easier to use.
It should be pretty straightforward, as described in the following:
[https://help.github.com/articles/adding-a-license-to-a-repository/](url)

MIT License would be nice, but it's obviously up to you. You can choose a license using:
[https://choosealicense.com](url)

**Comment by ojwoodford** [comment]
Thanks for the request. I just added the MIT license.
